### ISSUE TITLE
`check-column-name-contract` config for one-way enforcement

### ISSUE THREAD

**Issue by JFrackson** [Montreal-Analytics/dbt-gloss#121]
**Describe the feature you'd like**
Currently the `check-column-name-contract` hook works both ways: your pattern specified must always align with that data type, and every occurrence of that data type must align with the pattern.

This is not always desirable for specific patterns such as the following: you want to enforce that timestamps are being used for columns named `UPDATED_AT` and `LOADED_AT` but not necessarily all columns that end with `_AT`. 

```
hooks:
      - id: check-column-name-contract
        alias: check-updated-timestamp-name-contract
        name: Check updated_at name contract
        args: [--pattern, "UPDATED_AT", --dtype, TIMESTAMP_NTZ]
      - id: check-column-name-contract
        alias: check-load-timestamp-name-contract
        name: Check loaded_at name contract
        args: [--pattern, "LOADED_AT", --dtype, TIMESTAMP_NTZ]
```

One proposal is to add another config to this hook to indicate if you want to run it bidirectionally, unidirectionally for matching the pattern (i.e. every occurrence of the pattern must match the data type), or unidirectionally for the data type (i.e. every occurrence of the data type must match the pattern). 

Note, this is definitely related to the active discussion/work that's going on around [dbt contracts](https://github.com/dbt-labs/dbt-core/discussions/6726). I think this would still be very valuable and flexible in dbt-checkpoint, however, so I would love to see this support added!

**Additional context**
