### ISSUE TITLE
CLI - Command Line Interface

### ISSUE THREAD

**Issue by andresionek91** [Montreal-Analytics/dbt-gloss#123]
It would be nice to have a cli available for use. 
* Sometimes you want to run a single check and using pre-commit for that is a bit clumsy. A cli would provide a much better interface.
* In our case, for example, we run all of our pre-commit hooks using a local repo + poetry. Like this:
```
repos:
  - repo: local
    hooks:
      - id: dbt-compile
        name: Run dbt compile
        entry: poetry run dbt compile --project-dir src/snowflake --profiles-dir .dbt
        pass_filenames: false
        language: system
        types: [file, sql]
``` 
When running `dbt-checkpoint` directly from the hooks project, it doesn't use the poetry environment and can't find the dependencies (such as dbt). i get a: `FileNotFoundError: [Errno 2] No such file or directory: 'dbt'`

Overall, adding a CLI would greatly improve the project's flexibility and expand the use cases.

Was adding a CLI ever considered? Is it on the roadmap/future plans?

If it is something desirable by the maintainers, I volunteer to implement it and open the relevant PRs.
