### ISSUE TITLE
feat: add support for `DBT_TARGET_PATH` environment variable

### ISSUE THREAD

**Issue by menzenski** [Montreal-Analytics/dbt-gloss#134]
**Describe the feature you'd like**
It'd be great to have the `manifest.json` discovered automatically via the `DBT_TARGET_PATH` environment variable https://docs.getdbt.com/reference/project-configs/target-path#configuration. This seems to relate to https://github.com/dbt-checkpoint/dbt-checkpoint/issues/67 but this environment variable wasn't called out there specifically, so I'm opening a new issue.

**Additional context**
I am running dbt-core within a [Meltano](https://meltano.com/) project. I have things working fine with this set of pre-commit hooks (they are great!), but my configuration feels very verbose at the moment due to the fact that my dbt project is located in a subdirectory of the Meltano project, which itself is a subdirectory in my repository.

Here's an example pre-commit config file:

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.1.0
    hooks:
      # model checks
      - id: check-script-semicolon
        args:
          - --manifest
          - src/.meltano/transformers/dbt/target/manifest.json
          - --
      # script checks
      - id: check-script-has-no-table-name
        args:
          - --manifest
          - src/.meltano/transformers/dbt/target/manifest.json
          - --
      - id: check-script-ref-and-source
        args:
          - --manifest
          - src/.meltano/transformers/dbt/target/manifest.json
          - --
      # source checks
      # macro checks
      # modifiers
      # dbt commands
```

As you can see, I need to pass the `--manifest` path explicitly to every hook. 

It would be great to have these checks support the `DBT_TARGET_PATH` environment variable. Ideally, I could set `DBT_TARGET_PATH=src/.meltano/transformers/dbt/target` in my environment, and the scripts would be able to locate the `manifest.json` file within that target directory without me needing to set it explicitly on each hook like this.

I'll be happy to try to contribute to this fix if there's support for it.
