### ISSUE TITLE
dbt compile hook: add 'project-dir' parameter

### ISSUE THREAD

**Issue by paulfry-payroc** [Montreal-Analytics/dbt-gloss#142]
_Note:_ I've created the recommended [.dbt-checkpoint.yaml](https://github.com/dbt-checkpoint/dbt-checkpoint#setting-dbt-project-root), but still running into the below issue:

**Describe the feature you'd like**

* My dbt project files are stored within a sub-directory, so I'm unable to use the [`dbt-compile`](https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/HOOKS.md#dbt-compile) hook as-is.
* To get it working, I need to use the `--cmd-flags` flag to provide custom additional parameters. E.g.:

```yaml
hooks:
    - id: dbt-compile
       args: ["--cmd-flags", "++project-dir", "<MY_DBT_PROJECT_DIR>", "--"]
```
* The `project-dir` flag is very common & the above feels clunky/unintuitive.

---

**Ideal Target State**

The target state of the required code would ideally look like the following:

```yaml
hooks:
    - id: dbt-compile
       args: ["--project-dir", "<MY_DBT_PROJECT_DIR>"]
```

**Additional context**
