### ISSUE TITLE
check-model-parents-and-childs does not consider seeds as parents

### ISSUE THREAD

**Issue by mmartinenvato** [Montreal-Analytics/dbt-gloss#153]
**Describe the bug**

The `check-model-parents-and-childs` hook does not consider seeds as parents, so if a model only has a seed as a parent, it throws a failure when configured to have `--min-parent-count` > 0

**To Reproduce**

1. Add hook to pre-commit config:

```yaml
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.1.1
    hooks:
      - id: check-model-parents-and-childs
        args: ["--min-parent-cnt", "1", "--"]
```

2. Create seed under `seeds` directory

`seeds/<schema>/cfg_countries.csv`
```csv
country_code_iso_alpha2,country_code_iso_alpha3,country_code_iso_numeric,country_name,world_region,continent,currency_code,currency_name
AD,AND,020,"Andorra",Europe,Europe,EUR,Euro
AE,ARE,784,"United Arab Emirates",Asia,Asia,AED,Dirham
...
```

`seeds/_seeds.yml`

```yaml
version: 2

seeds:
  - name: cfg_countries
     schema: <schema>
  ...
```

3. Create model under `models` directory which references the seed as a parent

`models/<schema>/dim_countries.sql`

```sql
with
country as (
    select * from {{ ref('cfg_countries') }}
)
select * from country
```

`models/_models.yml`

```yaml
version: 2

models:
  - name: dim_countries
```

4. Run dbt seed and dbt build so model is in manifest (as required by the hook)

5. run pre-commit and see error:

```sh
pre-commit run check-model-parents-and-childs
Check the model has a parents/childs.....................................Failed
- hook id: check-model-parents-and-childs
- exit code: 1

dim_countries: has 0 min, but min 1is/are required.
```

**Expected behavior**

The hook recognises a seed as a parent for the purposes of a min-parent-count

**Version:**
`v1.1.1`

**Additional context**
