### ISSUE TITLE
check-model-has-tests-by-group registering zero tests even though it has them

### ISSUE THREAD

**Issue by VDFaller** [Montreal-Analytics/dbt-gloss#158]
**Describe the bug**
It seems this test has some reason that it fails.  

**To Reproduce**
1. dbt compile
2. pre-commit run -all-files check-model-has-tests-by-group
3. errors with `table2: has only 0 test(s) from ['unique', 'expect_compound_columns_to_be_unique'].`
My yaml's look fine.  In this instance table1 passes fine but table 2 doesn't
```yml
  - name: table1
    description: some stuff
    columns: 
      - name: id
        tests: 
          - unique
          - not_null

  - name: table2
    description: other stuff
    columns: 
      - name: id
        tests: 
          - unique
          - not_null
```
**Expected behavior**
That it passes

**Version:**
v1.0.0

**Additional context**
I find it too concidental that all of the failures have `demand_plan` in the table name,

**Comment by VDFaller** [comment]
Tried upgrading to see if that would help with this as my yaml. 

```yaml
repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.1.1
    hooks:
      # source tests
      - id: check-source-table-has-description #Ensures that the source table has a description in the properties file (usually schema.yml)
        verbose: true
      # model tests
      - id: check-model-has-description
      # - id: check-model-has-all-columns # need to comment out until I figure out https://github.com/dbt-checkpoint/dbt-checkpoint/issues/146
      - id: check-model-has-tests-by-group # Ensures that all models have a grain tests
        args: 
          - "--tests"
          - "unique"
          - "expect_compound_columns_to_be_unique"
          - "--test-cnt"
          - "1"
          - "--"
``` 

and found something else strange, if I change it to.  

```yaml
repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.1.1
    hooks:
      # model tests
      - id: check-model-has-description
      - id: check-model-has-tests-by-group # Ensures that all models have a grain tests
        args: 
          - "--tests"
          - "unique"
          - "dbt_expectations.expect_compound_columns_to_be_unique"
          - "--test-cnt"
          - "1"
          - "--"
```
Suddenly my `check-model-has-description` test fails.  I'm not even touching that test.  I have no idea what's going on.  But it's very binary.  If I do the top one my `check-model-has-description` passes, bottom one, fails.
