### ISSUE TITLE
check_model_has_tests_by_name being applied to all models

### ISSUE THREAD

**Issue by SantiASC** [Montreal-Analytics/dbt-gloss#219]
**Describe the bug**
When using pre-commit and committing a change of a file in the root directory that is not related to a dbt model (i.e. change to the .pre-commit-config.yaml), the check_model_has_tests_by_name hook checks across all available models in the manifest.json, this happens even if an exclude argument has been specified. 

Also, related to the --exclude argument, the example presented in HOOKS.md shows the following example:
`args: ["--test-cnt", "1", "--exclude models/demo", "--"]`
However, this syntax generates an error, I believe this should be updated to:
` args: ["--test-cnt", "1", "--exclude", "models/demo", "--"]`

**To Reproduce**
1. Add pre-commit hook to .pre-commit-config.yaml
```
   - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.1
    hooks:
      - id: check-model-has-tests-by-name
        args: ["--tests", "unique=1","--exclude",  "^(?!models/).*" ,"--"]
```

2. Stage and commit the .pre-commit-config.yaml change
3. pre-commit fails with all models in the **project** that fail the criteria (i.e. all models that do not have a unique test)

**Expected behavior**
The expected behavior is that this test checks only for dbt models or corresponding properties yml files that are committed or that using the exclude argument we can specify which files should be excluded. For example using the regex expression  "^(?!models/).*" would exclude committed changes that are not part of the models folder. 

**Version:**
v2.0.1

**Additional context**
In this attached image you can see that check-model-has-test-by-name failed even when .pre-commit-config.yaml file was the only change. This is not specific to change to pre-commit-config file, changes to other files like project.yml also trigger this behavior.
![test-by-name-result](https://github.com/dbt-checkpoint/dbt-checkpoint/assets/28426331/f9e76503-c2ad-4201-b568-bd18ff825395)
