### ISSUE TITLE
`Check_model_has_all_columns` does not work as expected

### ISSUE THREAD

**Issue by SuperbTUM** [Montreal-Analytics/dbt-gloss#227]
**Describe the bug**

Hello team, I followed the readme instructions on the use scenario of `check_model_has_all_columns` with the following code:
```
repo: https://github.com/dbt-checkpoint/dbt-checkpoint
rev: v2.0.1
hooks:
  - id: dbt-parse
    args: ["--cmd-flags", "++profiles-dir", "dbt", "++project-dir", "dbt"]
  - id: dbt-docs-generate
    args: [ "--cmd-flags", "++no-compile", "++profiles-dir", "dbt", "++project-dir", "dbt", "++threads", "4" ]
  - id: check-model-has-all-columns
```
And I deliberately removed one column in the model (sql) but keep the column description (yaml), hoping that the pre-hook would catch the error, however, it did not as the check always passed. Anything I understand incorrectly? Thanks.

**To Reproduce**
1. what is in the .pre-commit-config.yaml
```
repo: https://github.com/dbt-checkpoint/dbt-checkpoint
rev: v2.0.1
hooks:
  - id: dbt-parse
    args: ["--cmd-flags", "++profiles-dir", "dbt", "++project-dir", "dbt"]
  - id: dbt-docs-generate
    args: [ "--cmd-flags", "++no-compile", "++profiles-dir", "dbt", "++project-dir", "dbt", "++threads", "4" ]
  - id: check-model-has-all-columns

```
2. Remove a random column from a model under `dbt/models/` folder, which I can confirm it is a model, not source.
3. Run pre-commit, but it passed.

**Expected behavior**
I expect the pre-commit check failed as there is a deleted column.

**Version:**
v2.0.1

**Additional context**
N/A
