### ISSUE TITLE
check-column-name-contract exclude doesn't seem to work correctly

### ISSUE THREAD

**Issue by chrishuyghe** [Montreal-Analytics/dbt-gloss#242]
**Describe the bug**
check-column-name-contract not excluding specific columns even when defined in args.

**Steps to Reproduce**
1. pre-commit yml file looks like this:
```
repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v2.0.3
  hooks:  
    - id: check-column-name-contract
        args: ["--pattern", "^(is|has|do)(_.*)?|.*(_(is|has|do))(_.*)?$", --dtype, BOOL, "--exclude", "^is_gift$", "--"] 
```

2. scenario:
is_gift is a string and therefore it should be excluded, but we keep getting the warning that it is a string instead of a bool

3. output looks like this:
```
Check column name contract...............................................Failed
- hook id: check-column-name-contract
- exit code: 1

model model.xxx__orders, in file xxx__orders.sql 
is_gift: name matches regex pattern ^(is|has|do)(_.*)?|.*(_(is|has|do))(_.*)?$ and is of type STRING instead of BOOL.
```

**Expected Behavior**
No warnings should be thrown in this case

**version**
version:2.0.3
