### ISSUE TITLE
check-model-has-description and check-model-has-meta-keys not working for snapshots.

### ISSUE THREAD

**Issue by nicor88** [Montreal-Analytics/dbt-gloss#244]
**Describe the bug**
I tried to add check-model-has-meta-keys and check-model-has-description to my snapshots.

Here the configuration:

```
  - id: check-model-has-description
    name: Check that a snapshot has a description
    files: ^snapshots/
  - id: check-model-has-meta-keys
    name: Check that a snapshot has an owner
    files: ^snapshots/
    args: ['--meta-keys', 'owner', '--']
```
but the checks keep telling me that I need to put an owner.

Here my schema.yaml
```

snapshots:
  - name: my_table
    description: "Snapshot to track changes ...."
    meta:
      owner: "my-user"
```

**To Reproduce**
1. add dbt-checkpoint hooks as described above
2. create a dbt snapshots

**Expected behavior**
I expect that the checks don't fail as I have an owner and a description for my snapshot.

**Version:**
v1.2.1
