### ISSUE TITLE
`dbt-parse` hook failing with snapshot configuration error

### ISSUE THREAD

**Issue by stevenconnorg** [Montreal-Analytics/dbt-gloss#247]
**Describe the bug**
- `dbt parse` hook failing with error:
```
dbt parse................................................................Failed
- hook id: dbt-parse
- exit code: 1

Executing cmd: `dbt parse`
14:58:28  Running with dbt=1.8.3
14:58:28  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
14:58:29  Registered adapter: redshift=1.8.1
14:58:29  Unable to do partial parsing because saved manifest not found. Starting full parse.
14:58:54  Encountered an error:
Parsing Error
  at path []: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.
```

**To Reproduce**
1. dbt checkpoint action:
```
name: dbt-checkpoint

jobs:
  pre-commit:
    runs-on: 
      group: datasci
    env:
      DBT_ENV_SECRET_DB: ${{ secrets.DBT_ENV_SECRET_DB }}
      DBT_ENV_SECRET_HOST: ${{ secrets.DBT_ENV_SECRET_HOST }}
      DBT_ENV_SECRET_DEV_PASSWORD: ${{ secrets.DBT_ENV_SECRET_DEV_PASSWORD }}
      DBT_DEV_SCHEMA: ${{ secrets.DBT_DEV_SCHEMA }}
      DBT_DEV_USER: ${{ secrets.DBT_DEV_USER }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install pre-commit
        run: pip install pre-commit

      - id: file_changes
        uses: tj-actions/changed-files@v44

      - id: dotenv
        uses: falti/dotenv-action@v1.0.4

      - name: Run dbt checkpoint
        uses: dbt-checkpoint/action@v0.1
        with:
          extra_args: --files ${{ steps.file_changes.outputs.all_changed_files}}
          dbt_version: 1.8.3
          dbt_adapter: dbt-redshift

```
2. precommit yml file (`dbt-deps` hook runs fine, `dbt-parse` fails, and others are skipped) :
```
repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v2.0.2
  hooks:
  - id: dbt-deps
  - id: dbt-parse
  - id: check-script-semicolon
  - id: check-script-has-no-table-name
    args: ["--ignore-dotless-table", "--"]
  - id: check-script-ref-and-source
``` 
3. Snapshot files have config with the required settings:
```
{% snapshot some_snapshot %}

    {{
        config(
        target_schema = generate_schema_name('some_scd_schema'),
        unique_key = 'some_unique_key',
        strategy = 'check'
    )
    }}
   
   ...

```

**Expected behavior**
- We should be able to parse the project without getting snapshot errors during CI/CD job
-  tried setting the schema settings in the `dbt_project.yml`, thinking that maybe it wasn't able to pick up the snapshot-level configurations, but this didn't seem to help.

**Version:**
v2.0.2

**Additional context**
- Perhaps using the `generate_schema_name` macro in the `target_schema` config is tripping it up? We use the macro `generate_schema_name` to materialize in the `dev` schema if running in `dev`, so I didn't try hard-coding to the `prod` schema, since this is our intended development workflows.  I'm not sure why this would only happen in the package, though, since we don't get these errors when we run `dbt parse` outside of this package.
