### ISSUE TITLE
`check-model-has-properties-file` hook fails for versioned model with properties file

### ISSUE THREAD

**Issue by vknezovic1309** [Montreal-Analytics/dbt-gloss#258]
**Describe the bug**
We are running pre-commit check (v2.0.3) in our CI/CD. 
Hook `check-model-has-properties-file` fails for certain models (versioned models) with the following error: 

`Check the model has properties file......................................Failed
- hook id: check-model-has-properties-file
- exit code: 1

project_name/models/example_model.sql: does not have model properties defined in any .yml file.`

**Note**: real model path and files are replaced with examples to not reveal potentially sensitive information.

**To Reproduce**
1. Create .pre-commit-config file that includes the `check-model-has-properties-file` hook
2. Create version 1 of your model. The file name is: `project_name/models/example_model.sql`
**Note**: this model does not have the version suffix as we support the aliases.
Example .sql file: 
```
{{ config( materialized='table' ) }}

select
    field1,
    field2,
    field3,
    field4
from {{ ref('source_name') }}
```
3. Define model properties file `example_model.yaml`
```
version: 2

models:
  - name: example_model
    description: |
      Example model table
    config:
      contract:
        enforced: true
    latest_version: 1
    columns:
      - name: field1
        description: |
          Field1 description
        data_type: integer
        constraints:
          - type: not_null
        data_tests:
          - unique
      - name: field2
        description: |
          Field2 description
        data_type: string
        constraints:
          - type: not_null
      - name: field3
        description: Field3 description
        data_type: date
      - name: Field4
        description: Field 4 description
        data_type: integer
    versions:
      - v: 2
        columns:
          - include: all
            exclude: [field4]
      - v: 1
        access: public
        config:
            alias: example_model
```
4. Create the second version of the model, that will have `field4` excluded. Name the file `project_name/models/example_model_v2.sql`
```
{{ config( materialized='table' ) }}

select
    field1,
    field2,
    field3
from {{ ref('source_name') }}
```
5. Trigger the pre-commit check.

**Expected behavior**
Pre-commit check should pass with no reported errors as model has defined the properties file. 

**Version:**
v2.0.3

**Additional context**
We are running pre-commit check in GitHub actions set up.
