### ISSUE TITLE
`check-model-has-properties-file` hook fails for versioned model without _v suffix

### ISSUE THREAD

**Issue by RecMarkoL** [Montreal-Analytics/dbt-gloss#259]
**Describe the bug**
We are running pre-commit check (v2.0.4) in our GitHub CI/CD.
Hook check-model-has-properties-file fails for certain models (versioned models) with the following error:

```
Check the model has properties file......................................Failed

- hook id: check-model-has-properties-file
- exit code: 1
models/<model_path>/<model_name>.sql: does not have model properties defined in any .yml file.
```

**To Reproduce**

- Create .pre-commit-config file that includes the check-model-has-properties-file hook
- Create version 1 of your model. The file name is: `models/example_model.sql`
- Create version 2 of your model. Rename v1 with suffix `_v1` and leave v2 without suffix since dbt docs state `it's also possible to define the "latest" version in <model_name>.sql (no suffix), without additional configuration.`
- Recap: `example_model_v1.sql` and `example_model.sql` models now exist

Define model properties in example_model.yaml
```
version: 2

      - name: example_model
        description: "Desc"
        latest_version: 2
        versions:
          - v: 1 # First version
          - v: 2 # Second version
```

**Expected behavior**
Pre-commit check should pass with no reported errors as model has defined the properties file.

Version:
v2.0.4

Additional context
We are running pre-commit check in GitHub actions.

**Comment by BAntonellini** [comment]
Hi @RecMarkoL, indeed there was a bug discovering versioned property files. Thanks for pointing it out.

SQL files had to be explicitly named following `_vX` for versions to be taken into account.

Until we release a new dbt-checkpoint version, could you try this same scenario using `rev: 9c7b3375bd8b1847ec88a85a87ea4b8104c0f454`?

**Comment by RecMarkoL** [comment]
Sorry for delay in response.

I just tried the mentioned revision and ran `pre-commit run --all-files`. Most of the versioned files worked as expceted, however my old version files didn't.

I keep my old versions in separate folder. As an example my models are in `models/staging/model1.sql` and models defined in `models/staging/_staging_models.yml`. The current version models are named without suffix as mentioned in the issue. My older models are in subfolder `models/staging/_old_versions/model1_v1.sql`.

The `check-macro-has-description` fails on the old model versions.

Model is defined like this in the yaml:
```
      - name: model1
        description: "Some description"
        latest_version: 2
        versions:
          - v: 1 # First version
            deprecation_date: 2024-02-21
          - v: 2 # Second version
```

Error states `does not have model properties defined in any .yml file.` for each of the old version files
