### ISSUE TITLE
`check-model-has-description` in 2.0.6 does not ignore excluded files

### ISSUE THREAD

**Issue by FrankTub** [Montreal-Analytics/dbt-gloss#272]
**Describe the bug**
My `.pre-commit-config.yml` looks like:

```yaml
fail_fast: true
repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v2.0.6
  hooks:
...
  - id: check-model-has-description
    exclude: (analysis/|snapshots/|macros/|.gitlab-ci.yml)
```

But the resulting error is:

```shell
Check the model has description..........................................Failed
- hook id: check-model-has-description
- exit code: 1
snapshots/snapshot_category_groups/snapshot_category_groups.sql: does not have defined description or properties file is missing.
...
```

**To Reproduce**

1. Create a snapshot sql file and some statement
2. Skip the yml for that snapshot
 Run the above mentioned hook

**Expected behavior**
To ignore all files mentioned in `exclude`

**Version:**
v2.0.6

**Additional context**
Also looks like the performance of that hook significantly declined in `v2.0.6` vs `v2.0.4`
