### ISSUE TITLE
check-model-has-all-columns could not find catalog.json

### ISSUE THREAD

**Issue by TiansuYu** [Montreal-Analytics/dbt-gloss#285]
**Describe the bug**
I have a pre-commit file set as follows 
```
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.6
    hooks:
      - id: dbt-clean
      - id: dbt-deps
      - id: dbt-compile
      - id: dbt-docs-generate
      - id: check-script-semicolon
      - id: check-script-has-no-table-name
      - id: check-script-ref-and-source
      - id: remove-script-semicolon
      - id: check-model-has-all-columns
        args: ["--exclude", "models/reporting"]
      - id: check-macro-has-description
 ```
And this gives me the following result 
```
dbt clean................................................................Passed
dbt deps.................................................................Passed
dbt compile..............................................................Passed
dbt docs generate........................................................Passed
Check the script does not contain a semicolon............................Passed
Check the script has not table name......................................Passed
Check the script has existing refs and sources...........................Passed
Remove script semicolon..................................................Passed
Check the model has all columns in properties file.......................Failed
- hook id: check-model-has-all-columns
- exit code: 1

Unable to find model `model.xyz` in catalog file. Make sure you run `dbt docs generate` before executing this hook.
Unable to find model `model.xyz` in catalog file. Make sure you run `dbt docs generate` before executing this hook.
...
```
It seems that `check-model-has-all-columns` has completely ignored by `dbt-docs-generate`. FYI, this only happens on Github Action, but not locally. 

**Expected behavior**
`check-model-has-all-columns` should find an available `catalog.json` generated by `dbt-docs-generate`. 

**Version:**
- dbt version: 1.8.9
- hook version: 2.0.6
