### ISSUE TITLE
check-source-has-freshness miss required freshness parameters too strict

### ISSUE THREAD

**Issue by cedric-orange** [Montreal-Analytics/dbt-gloss#307]
**Describe the bug**
If you set `check-source-has-freshness` args to required `error_after` only, if you have a source with both `warn_after` and `error_after`  check-source-has-freshness fails.

**To Reproduce**
1. Set a source file with fo exemple:
```yml
    loaded_at_field: tech_timestamp_load
    freshness: 
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}
```
2. set pre-commit config to:
```yml
  - id: check-source-has-freshness
    args: ["--freshness", "error_after", "--"]
```

3. check-source-has-freshness fails with:
```bash
Check the source has the freshness.......................................Failed
- hook id: check-source-has-freshness
- exit code: 1

source_example: miss some required freshness parameters:
- 
```

**Expected behavior**
As in our source file there is both  `warn_after` and `error_after` , check should pass.

**Version:**
v2.0.7

**Additional context**
In this file https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/dbt_checkpoint/check_source_has_freshness.py#L47

This test :

`if not (freshness == required_freshness):`

should be replaced by : 

`if not required_freshness in freshness:`
