### ISSUE TITLE
Snapshots trigger check-model-has-properties-file

### ISSUE THREAD

**Issue by eugenekim-orrum** [Montreal-Analytics/dbt-gloss#41]
**Describe the bug**
Snapshot tables located in the /snapshots folder trigger the check-model-has-properties-file check, even with a property file defined per [dbt documentation](https://docs.getdbt.com/reference/snapshot-properties). Changing the "snapshots" header to "model" does not change the outcome.

**To Reproduce**
1. Create a snapshot SQL file.
```
{% snapshot <snapshot name> %}

{{
    config(
        target_database=<snapshot db>,
        target_schema=<snapshot schema>,
        unique_key=<snapshot key>,

        strategy='timestamp',
        updated_at=<snapshot updated_at>,
        invalidate_hard_deletes=True,
    )
}}

select * from {{ ref(<snapshot model>) }}

{% endsnapshot %}
```
2. Create a snapshot properties YAML file.
```
version: 2

snapshots:
  - name: <snapshot name>
    description: <markdown_string>    
	config:
      target_schema: <snapshot schema>
      target_database: <snapshot db>
      unique_key: <snapshot key>
      strategy: timestamp
      updated_at: <snapshot updated_at>
```

**Expected behavior**
The check-model-has-properties-file check should pass.

**Version:**
v0.1.0
