### ISSUE TITLE
Issue with the check-column-name-contract hook

### ISSUE THREAD

**Issue by john-jerome** [Montreal-Analytics/dbt-gloss#42]
Hello folks,

first I noticed that [on this page](https://github.com/offbi/pre-commit-dbt/blob/main/HOOKS.md) when clicking on `check-column-name-contract` you get a 404 page. However, today I've decided to actually use this hook in my project and got the following error:

```[ERROR] `check-column-name-contract` is not present in repository https://github.com/offbi/pre-commit-dbt.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.```

**To Reproduce**
1. add `check-column-name-contract` to your config file
2. run pre-commit

**Version:**
v1.0.0

**Comment by john-jerome** [comment]
Hey, I believe this issue is still relevant - the web page is broken and the corresponding hook still doesn't work.

**Comment by robertdefilippi** [comment]
I'm also encountering the same error with 1.0.0

**Comment by robertdefilippi** [comment]
Can confirm using this commit outlined here, fixes the issue of not being able to find the command 🙂 

https://github.com/offbi/pre-commit-dbt/issues/56

.pre-commit.yaml
```
...
  - repo: https://github.com/offbi/pre-commit-dbt
    rev: ea9c6bafbca375250baa9c21b8ddf9207d9c0160
    hooks:
        - id: check-model-has-description
        - id: check-model-name-contract
          args: [--pattern, "(base_|stg_).*"]
          files: models/staging/
...
```

However, I'm not sure the command is running correctly as I keep getting an error.

The model is under this path `models/staging/seeds/stg_countries.sql` and `check-model-name-contract` keeps failing even though it starts with `stg_` I'm also getting an error code which is not entirely helpful at debugging what the issue ie.

```
dbt docs generate........................................................Failed
- hook id: dbt-docs-generate
- exit code: 1

Executing cmd: `dbt docs generate`

Check staging models start with base_ or stg_............................Failed
- hook id: check-model-name-contract
- exit code: 1
```
