### ISSUE TITLE
Source test results in parser error when using sqlfluff

### ISSUE THREAD

**Issue by andrewpblee** [Montreal-Analytics/dbt-gloss#51]
**Describe the bug**
When trying to run any test on a source, in this case the loader test (but it's the same for any other), I get an parser error with the following: 
```
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in ".sqlfluff", line 2, column 1
```

I'm using sqlfluff as my linter, and it appears the source test is  trying to compile this file as yaml.

**To Reproduce**
1. Create a project using dbt v1 and install sqlfluff v0.9.*
2. Create Source Yamls
3. Run any source test

**Expected behavior**
The source test should succeed or fail, rather than error. 

**Version:**
v1.0.0

**Additional context**
I've had to switch my `.pre-commit-config.yaml` from `rev` to `sha` to get around the issue highlighted in #26 

```
repos:
  - repo: https://github.com/offbi/pre-commit-dbt
    sha: v1.0.0
    hooks:
#      dbt commands
      - id: dbt-deps
      - id: dbt-compile
        args: [ "--cmd-flags", "++profiles-dir", "." , "--"]
      - id: dbt-docs-generate
        args: [ "--cmd-flags", "++profiles-dir", "."]

#     Script Checks
      - id: check-script-semicolon
      - id: check-script-ref-and-source

#     Model Checks
      - id: check-model-has-properties-file


#     Source Checks
      - id: check-source-has-loader
```

All other checks pass except for `check-source-has-loader`
