### ISSUE TITLE
Github action example fails to run

### ISSUE THREAD

**Issue by miki-lwy** [Montreal-Analytics/dbt-gloss#56]
**Describe the bug**
Trying to use github action using example in the README but it fails with invalid argument error.

**To Reproduce**
In the .github/workflows/action.yaml
```
uses: offbi/pre-commit-dbt@ea9c6bafbca375250baa9c21b8ddf9207d9c0160
with:
  args: run --files ${{ steps.file_changes.outputs.files }}
```

and get the following errors when the github action runs:
```
usage: pre-commit [-h] [-V]
                  {autoupdate,clean,hook-impl,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,help}
                  ...
pre-commit: error: argument command: invalid choice: 'run --files ' (choose from 'autoupdate', 'clean', 'hook-impl', 'gc', 'init-templatedir', 'install', 'install-hooks', 'migrate-config', 'run', 'sample-config', 'try-repo', 'uninstall', 'help')
```

**Additional context**
I am using the latest commit hash: ea9c6bafbca375250baa9c21b8ddf9207d9c0160

**Comment by tomsej** [comment]
Thank you @miki-lwy I will take a look

**Comment by natarajanc-prodigygame** [comment]
i faced the same issue

**Comment by simon-tarr** [comment]
I'm also getting this issue, running the latest commit ([cc144b9](https://github.com/offbi/pre-commit-dbt/commit/cc144b9a1a24112428d9a52a66905815990e4554)). Is there a workaround to this error for the time being?

**Comment by natarajanc-prodigygame** [comment]
hi @tomsej  any chance you had  a chance to take a look at this ? thanks for making this package - the github actions would really help us

**Comment by seamus-mckinsey** [comment]
FWIW, I ended up not using the GHA and just installed precommit in the workflow so I could call the hooks I specifically wanted, which works for me:
```
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Get changed files
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
      - name: run pre-commit-dbt added files
        if: steps.get_file_changes.outputs.files_added != '' && always()
        shell: bash
        run: |
          pre-commit run check-script-has-no-table-name --files ${{ steps.get_file_changes.outputs.files_added }} |

```
