### ISSUE TITLE
Docker image pull down image action fails

### ISSUE THREAD

**Issue by grace-cityblock** [Montreal-Analytics/dbt-gloss#57]
**Describe the bug**
When hooking to the docker file, getting error `invalid reference format` when the build runs the step to pull the action image. 

Pull down action image 'offbi:pre-commit-dbt:v1.0.0'
  /usr/bin/docker pull offbi:pre-commit-dbt:v1.0.0
  invalid reference format
  Warning: Docker pull failed with exit code 1, back off 3.[2](https://github.com/cityblock/mixer/runs/5222975541?check_suite_focus=true#step:2:2)75 seconds before retry.
  
**To Reproduce**
1. add new file `.github/workflows/pre-commit-dbt.yml`:
```
name: pre-commit

on:
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ' '
    - uses: offbi/pre-commit-dbt@v1.0.0
      env:
        DB_PASSWORD: ${{ secrets.SuperSecret }}
      with:
        args: run --files ${{ steps.file_changes.outputs.files}}
```

2. add the following code to existing (or create new) `.pre-commit-config.yaml`
```
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-script-has-no-table-name
    files: ^dbt
```
3. commit changes and create a pull request to trigger test build.

**Expected behavior**
Build test completes successfully.  

**Version:**
v1.0.0
(dbt version 0.21.0)

**Additional context**
I think it's odd that the yml file clearly shows `offbi/pre-commit-dbt@v1.0.0` for the step action, but when the docker pull command is passed the syntax is changed to `offbi:pre-commit-dbt:v1.0.0` (notice colons in place of slash & @).  Nowhere in the documentation does it list how to avoid this.
Also note: The "test" completes successfully if the following block is removed (all other steps run correctly):
```
    - uses: offbi/pre-commit-dbt@v1.0.0
      env:
        DB_PASSWORD: ${{ secrets.SuperSecret }}
      with:
        args: run --files ${{ steps.file_changes.outputs.files}}
```
So it seems that it's this specific docker image causing the issue.

**Comment by grace-cityblock** [comment]
@kristofernorwood for viz

**Comment by simon-tarr** [comment]
Is there a workaround to this bug while a fix is implemented? Thanks!
EDIT - Turns out there is although I'm not sure this is a good work around for everyone. I changed the version of pre-commit-dbt from @v1.0.0 to the latest (as of 23rd Feb 2022) commit. So my main.yml file now looks like:

```
- name: Build Docs
  uses: offbi/pre-commit-dbt@cc144b9a1a24112428d9a52a66905815990e4554
  env:
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  with:
    args: run --files ${{ steps.file_changes.outputs.files}}
```

**Comment by grace-cityblock** [comment]
> Is there a workaround to this bug while a fix is implemented? Thanks! EDIT - Turns out there is although I'm not sure this is a good work around for everyone. I changed the version of pre-commit-dbt from @v1.0.0 to the latest (as of 23rd Feb 2022) commit. So my main.yml file now looks like:
> 
> ```
> - name: Build Docs
>   uses: offbi/pre-commit-dbt@cc144b9a1a24112428d9a52a66905815990e4554
>   env:
>     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
>   with:
>     args: run --files ${{ steps.file_changes.outputs.files}}
> ```

Thank you for this @simon-tarr!  This got me past the reference format issue.  I'm still trying to get around passing arguments but that helped a lot.

**Comment by grace-cityblock** [comment]
Requesting suggestions here on above, since I have tried a multitude of things to handle this, including $ARGS in environment variables, checking out the work and comments in PR 48, and hacking my own fork to get around this, but it seems that the github action is escaping the args line as indicated both in @simon-tarr 's comment and in the original readme. By escaping, I mean that it is passing the entire args line as one command (not as a command + flag + argument).  The result is that it doesn't recognize what is passed as a command.  As an example, even if I pass nothing, it defaults to the "run --all-files" in the actions yaml, and returns this:
```"run --all-files"
usage: pre-commit [-h] [-V]
                  {autoupdate,clean,hook-impl,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,help}
                  ...
pre-commit: error: argument command: invalid choice: 'run --all-files' (choose from 'autoupdate', 'clean', 'hook-impl', 'gc', 'init-templatedir', 'install', 'install-hooks', 'migrate-config', 'run', 'sample-config', 'try-repo', 'uninstall', 'help')
```

Notice the line `invalid choice: 'run --all-files' ` - it's not seeing it as `run` with an added flag.  @tomsej have you seen this in your development?

**Comment by Aylr** [comment]
@grace-cityblock I've found a workaround you might find useful. I'm not using the dbt-pre-commit GitHub action at all, which doesn't bother me too much since it appears to be a thin wrapper anyway:

**Note I'm using the excellent [dbt-action](https://github.com/mwhitaker/dbt-action) pinned to the latest commit on main that fixes a bug that isn't released yet**.

```yaml
jobs:
  PreCommitChecks:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dbt dependencies
        uses: mwhitaker/dbt-action@56f1f21c8026df783c17f65743b17855b5be22d9
        with:
          dbt_command: "dbt deps --profiles-dir . --target=dev"

      - name: Build dbt docs  # the dbt pre-commit checks use assets compiled by dbt docs generate
        uses: mwhitaker/dbt-action@56f1f21c8026df783c17f65743b17855b5be22d9
        with:
          dbt_command: "dbt docs generate --profiles-dir . --target=dev"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit model checks
        run: pre-commit run --all-files
```
