### ISSUE TITLE
Improved ReadMe Documentation

### ISSUE THREAD

**Issue by simon-tarr** [Montreal-Analytics/dbt-gloss#59]
I'm relatively new to Github Actions so my issue here could totally be my lack of understanding of Actions in general. If that's the case, I apologise. However, I find the current ReadMe difficult to understand. I would benefit from improved documentation on what this Action is doing.

**Additional context**
Based on my current understanding, I believe that I have to first create a `.pre-commit-config.yml` file (modified to first run `dbt-compile` as I'm running this as a Github Action) and then save this in my project's root directory. For example, if I wished to build the documentation for my project I must define the following:

```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: dbt-compile
    args: ["--cmd-flags", "++profiles-dir", "."]
  - id: dbt-docs-generate
```
Presumably this would build the documentation in a folder called `~/target` as would be the case in default `dbt`? (I can't see any arguments in the [hook's documentation](https://github.com/offbi/pre-commit-dbt/blob/main/HOOKS.md#dbt-docs-generate) to suggest it's possible to change the directory.)

From here, things get fuzzy for me. In the current ReadMe under the [create new workflow section](https://github.com/offbi/pre-commit-dbt#create-new-workflow) we then see the following:

```
name: pre-commit

on:
  pull_request:
  push:
  branches: [main]

jobs:
  pre-commit:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v2
  - id: file_changes
    uses: trilom/file-changes-action@v1.2.4
    with:
      output: ' '
  - uses: offbi/pre-commit-dbt@v1.0.0
    env:
      DB_PASSWORD: ${{ secrets.SuperSecret }}
    with:
      args: run --files ${{ steps.file_changes.outputs.files}}
```
I don't at this point understand:

- What is `- id: file_changes`? What is `trilom/file-changes-action@v1.2.4` and why is it required when using `pre-commit-dbt`?
- How does `offbi/pre-commit-dbt` use `.pre-commit-config.yml`? Is the `pre-commit-config` file parsed with `run --files ${{ steps.file_changes.outputs.files}}`? Am I correct in thinking that somewhere in the above .yml, the Action will call `.pre-commit-config.yml` and run whatever is specified in this file?
- Is it necessary to create a `profiles.yml` file and keep this in the project's root dir when using Github Actions, or can all environment variables be stored in Github Secrets? It's not clear when this file is required ([dbt recommends](https://docs.getdbt.com/dbt-cli/configure-your-profile) that `profiles.yml` be kept in locally in `~/.dbt`)

Apologies for all the questions and thanks in advance for helping a newbie out!
