### ISSUE TITLE
Use enviornemental varaibles like $PWD

### ISSUE THREAD

**Issue by tcholewik** [Montreal-Analytics/dbt-gloss#67]
Give hooks access to environmental variables like:
 - PWD
 - DBT_PROFILES_DIR
 - DBT_PROJECT_DIR
 - DBT_ARTIFACT_STATE_PATH

I am not saying that all environmental variables need to be supported but those listed above are good candidates, alternatively, we could use plain python to mutate file paths into absolute ones but I'm not sure if there are any edge cases that might suffer as result.

The reason for above idea is I tried running this hook:
```yaml
  - repo: https://github.com/offbi/pre-commit-dbt
    rev: v1.0.0
    hooks:
      - id: dbt-compile
        files: "^dbt/.*(sql|yaml|yml)$"
        pass_filenames: false
        args:
          - "--cmd-flags"
          - "++project-dir"
          - "./dbt"
          - "++state"
          - "./dbt/target/HEAD"
          - "--models"
          - "state:modified"
```
dbt compile always fails while saying it cannot find a comparison manifest.
So I tried to run the same command in a regular shell rather than pre-commit `dbt compile -m state:modified --project-dir ./dbt --state=dbt/target/HEAD` and I still get the same error.
After some trial and error, it looks like `--state` only works if I give it an absolute path.

I find that having to specify an absolute path is a real bummer because the repo will probably be cloned to a different directory on each machine.  

What I am hoping to see is that I can either get rid of `--state` arg and use `DBT_ARTIFACT_STATE_PATH`  or expand `PWD` in `--state=$PWD/dbt/target/HEAD`

I am happy to tackle this myself but I would like to make sure first that this idea won't get pushback when I make the PR( assuming my implementation is reasonable of course).

`pre-commit` already seems to have some mechanisms to pass environmental variables I found this [issue](https://github.com/pre-commit/pre-commit/issues/2367) and they referenced a few examples of what the solution might look like( I believe that this already works but it just not documented well/at all).
