### ISSUE TITLE
`Check model name contract` hook problem with version

### ISSUE THREAD

**Issue by papost** [Montreal-Analytics/dbt-gloss#77]
When using the following pre commit config file

```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-model-name-contract
    args: [--pattern, "(rep__).*"]
    files: models/reporting
```

I get the following response
[ERROR] `check-model-name-contract` is not present in repository https://github.com/offbi/pre-commit-dbt.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.

Even if I run the `autoupdate` command the error message is the same. Am I missing something?
