### ISSUE TITLE
check-model-parents-and-childs for zero child check never runs

### ISSUE THREAD

**Issue by PeteCorbettWS** [Montreal-Analytics/dbt-gloss#85]
Attempting to use check-model-parents-and-childs hook to ensure that our data consumption layer models do not have any children does not fail when models DO have children

#### Steps to reproduce the behavior:
1. dbt project with a parent and child models
2. Add check-model-parents-and-childs with --max-child-cnt of zero
```yaml
  - id: check-model-parents-and-childs
    name: Check for child models in data consumption layers
    # manifest.json required
    args: ["--manifest","./pipelines/target/manifest.json","--max-child-cnt","0","--"]
    files: models/self_service/
```
#### Expected outcome:
Model that has a child is raised as failure

#### Actual outcome:
Hook passes

#### Version:
```yaml
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: 34a2341234675d7a6b61766b2c33bdd5c33d090b
```

#### Additional info:
Offending code appears to be checking for default (None) for the --max-child-cnt returning false for zero value i.e. 
```python 
 if req_cnt and req_operator(real_value, req_cnt):
     status_code = 1
     print(
...
```
may need to explicitly check for None?
```python
 if req_cnt is not None and req_operator(real_value, req_cnt):
   status_code = 1
     print(
...
```
